hydra:
  job:
    chdir: true
    name: diffusion_era_cosmo
  run:
    dir: ./outputs/training/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/era_cosmo

  # Model
  - model/era_cosmo_diffusion

  - model_size/normal

  # Training
  - training/era_cosmo_diffusion

  # Logging
  - logging/era_cosmo_diffusion
