hydra:
  job:
    chdir: true
    name: diffusion_era5_cosmo_test
  run:
    dir: /capstor/scratch/cscs/pstamenk/outputs/training/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/era_cosmo

  # Model
  - model/era_cosmo_diffusion

  - model_size/normal

  # Training
  - training/era_cosmo_diffusion

  # Inference visualization
  - generation/era_cosmo_training