hydra:
  job:
    chdir: true
    name: regression_era5_cosmo_all_channels
  run:
    dir: /capstor/scratch/cscs/mmcgloho/outputs/training/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/era_cosmo

  # Model
  - model/era_cosmo_regression

  - model_size/normal

  # Training
  - training/era_cosmo_regression

  # Inference visualization
  # - generation/era_cosmo_training

  # Logging
  - logging/era_cosmo_regression
