hydra:
  job:
    chdir: true
    name: diffusion_era5_cosmo_patched
  run:
    dir: ./outputs/training/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/anemoi_era_cosmo

  # Model
  - model/era_cosmo_diffusion_patched

  - model_size/normal

  # Training
  - training/era_cosmo_diffusion_patched

  # Logging
  - logging/era_cosmo_diffusion