hydra:
  job:
    chdir: true
    name: diffusion_era_real
  run:
    dir: ./outputs/training/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/anemoi_era_real

  # Model
  - model/era_real_diffusion_patched

  - model_size/normal_real

  # Training
  - training/era_real_diffusion_patched

  # Logging
  - logging/era_real_diffusion