hydra:
  job:
    chdir: true
    name: regression_era_cosmo
  run:
    dir: ./outputs/training/${hydra:job.name}


# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/anemoi_era_cosmo

  # Model
  - model/era_cosmo_regression

  - model_size/normal

  # Training
  - training/era_cosmo_regression

  # Logging
  - logging/era_cosmo_regression
