hydra:
  job:
    chdir: true
    name: regression
  run:
    dir: /iopsstor/scratch/cscs/pstamenk/outputs/${hydra:job.name}

# Get defaults
defaults:
  - _self_

  # Dataset
  - dataset/era_cosmo

  # Model
  - model/era_cosmo_regression

  # Training
  - training/era_cosmo_regression