FROM nvcr.io/nvidia/physicsnemo/physicsnemo:25.06
    
# setup and install eccodes 
# Install the system-level C binary and tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    libeccodes-dev \
    libeccodes-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
    
# Install the rest of dependencies.
RUN pip install \
    anemoi.datasets==0.5.41 \
    Cartopy==0.22.0 \
    xskillscore \
    scoringrules \
    mlflow \
    meteodata-lab \
    eccodes
