# Following some suggestions in https://meteoswiss.atlassian.net/wiki/spaces/APN/pages/719684202/Clariden+Alps+environment+setup

FROM ubuntu:22.04 as builder
#FROM nvcr.io/nvidia/pytorch:25.01-py3


# setup
RUN apt-get update && apt-get install python3-pip python3-venv -y
RUN pip install --upgrade \
        pip 
        #ninja
        #wheel
        #packaging
        #setuptools

# install the rest of dependencies
# TODO: Factor pydeps into a separate file(s)
# TODO: Add versions for things
RUN pip install \
        anemoi-datasets \
        cartopy \
        matplotlib \
        numpy \
        pandas \
        scipy \
        torch 

#RUN apt-get install libgdal-dev -y  # Old version 3.4.1, needs 3.5
#RUN apt-get install gdal-bin -y # Insufficient
RUN apt-get install curl -y
RUN apt-get install sudo -y
#RUN curl -sL "https://url.geocarpentry.org/gdal-ubuntu" | bash


#RUN pip install \ 
#        rasterio==1.3.9 \
 #       meteodata-lab[regrid]



