FROM jfrog.svc.cscs.ch/docker-group-csstaff/alps-images/ngc-physicsnemo:25.11-alps4-dev

WORKDIR /sourcecode

setup
RUN pip install --upgrade \
        pip

WORKDIR ../../

# install dependencies
RUN pip install mlflow

RUN pip install -e .
