FROM jfrog.svc.cscs.ch/docker-group-csstaff/alps-images/ngc-physicsnemo:25.11-alps4-dev

RUN pwd

RUN ls

RUN ls /sourcecode

# setup
# RUN pip install --upgrade \
#         pip

# WORKDIR ../../

# # install dependencies
# RUN pip install mlflow

# RUN pip install -e .
