name: fernanda
full_name: "Hurricane Fernanda"
lat_min: 0.0
lat_max: 30.0
lon_min: -135.0
lon_max: -105.0
dates: ["12", "13", "14", "15", "16", "17"]
analysis_dates: ["20230812"]
year: "2023"
month: "08"
pressure_threshold: 1013.25
