include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build
  - test

variables:
  PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/hirad-gen:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/docker/Dockerfile

test_job:
  stage: test
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  script:
    - cd /src
    - python src/hirad/eval/run_scoring.py 
  variables:
    SLURM_JOB_NUM_NODES: 1
    SLURM_NTASKS: 1
    USE_NCCL: cuda12
    FI_CXI_DISABLE_HOST_REGISTER: 1
    FI_MR_CACHE_MONITOR: userfaultfd
    NCCL_DEBUG: INFO

