# Hyperparameters
hp:
    training_duration: 500000
    # Training duration based on the number of processed samples
    total_batch_size: 64
    # Total batch size
    batch_size_per_gpu: "auto"
    # Batch size per GPU
    lr: 0.0002
    # Learning rate
    grad_clip_threshold: null
    # no gradient clipping for defualt non-patch-based training
    lr_decay: 1
    # LR decay rate
    lr_rampup: 0
    # Rampup for learning rate, in number of samples
    lr_decay_rate: 5e5
    # Learning rate decay threshold in number of samples, applied every lr_decay_rate samples.

# Performance
perf:
    fp_optimizations: amp-bf16
    # Floating point mode, one of ["fp32", "fp16", "amp-fp16", "amp-bf16"]
    # "amp-{fp16,bf16}" activates Automatic Mixed Precision (AMP) with {float16,bfloat16}
    dataloader_workers: 10
    # DataLoader worker processes
    songunet_checkpoint_level: 0 # 0 means no checkpointing
    # Gradient checkpointing level, value is number of layers to checkpoint
    # torch_compile: True
    # use_apex_gn: True

# I/O
io:
    print_progress_freq: 1024
    # How often to print progress
    save_checkpoint_freq: 25000
    # How often to save the checkpoints, measured in number of processed samples
    validation_freq: 5000
    # how often to record the validation loss, measured in number of processed samples
    validation_steps: 10
    # how many loss evaluations are used to compute the validation loss per checkpoint
    checkpoint_dir: .